# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- recent_posts
- archive
- emailist

# SubNav
subnav:
rss: "/atom.xml"

# Miscellaneous
google_analytics: UA-72042404-1
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

#gitalk settings
gitalk:
  enable: true
  owner: cautes
  repo: cautes.github.io 
  admin: cautes
  clientID: 00be5b58d4db21cf2f64
  clientSecret: e63df28d88b7c897123a1c6adefabaf70b8050a9


