# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- recent_posts
- weixin
- archive

# Miscellaneous
google_analytics: UA-72042404-1
baidu_tongji: true
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# 配置关注微信公众号
weixin: http://ww1.sinaimg.cn/small/67ab259fjw1f3j68qx11cj20760760t7.jpg

