# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
baidu_tongji: true
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: